version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-blog-app
    container_name: laravel-app
    restart: unless-stopped
    environment:
      APP_ENV: local
      APP_DEBUG: true
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/html/database/database.sqlite
    volumes:
      - .:/var/www/html:cached
      - vendor:/var/www/html/vendor  # ⬅️ ini solusi utama
      - storage:/var/www/html/storage
      - cache:/var/www/html/bootstrap/cache
      - telescope_public:/var/www/html/public/vendor
      - sqlite_data:/var/www/html/database
    ports:
      - "8000:80"
    networks:
      - laravel

  web:
    image: nginx:alpine
    container_name: laravel-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html:cached
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: laravel-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - laravel

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    ports:
      - "8025:8025"
    networks:
      - laravel

volumes:
  vendor: {}  # ⬅️ volume Docker untuk menyimpan /vendor internal
  storage: {}
  cache: {}
  telescope_public: {}
  sqlite_data: {}

networks:
  laravel:
